//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class comercioEntities : DbContext
    {
        public comercioEntities()
            : base("name=comercioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<entrega> entrega { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<tipoentrega> tipoentrega { get; set; }
        public virtual DbSet<vendedor> vendedor { get; set; }
    }
}
