//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public int IDEndereco { get; set; }
        public string Logradouro { get; set; }
        public short Numero { get; set; }
        public string Bairro { get; set; }
        public short IDCidade { get; set; }
        public int IDCliente { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
