//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrega
    {
        public int IDEntrega { get; set; }
        public string CodigoRastreio { get; set; }
        public byte IDTipoEntrega { get; set; }
        public int IDPedido { get; set; }
    
        public virtual pedido pedido { get; set; }
        public virtual tipoentrega tipoentrega { get; set; }
    }
}
